//
// File generated by /CERN/root/bin/rootcint at Tue Jun 20 18:58:51 2017

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME AnaDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "AnaDict.h"

#include "TCollectionProxyInfo.h"
#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void Analyze_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_Analyze(void *p = 0);
   static void *newArray_Analyze(Long_t size, void *p);
   static void delete_Analyze(void *p);
   static void deleteArray_Analyze(void *p);
   static void destruct_Analyze(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::Analyze*)
   {
      ::Analyze *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::Analyze >(0);
      static ::ROOT::TGenericClassInfo 
         instance("Analyze", ::Analyze::Class_Version(), "./../src/Analyze.h", 19,
                  typeid(::Analyze), DefineBehavior(ptr, ptr),
                  &::Analyze::Dictionary, isa_proxy, 4,
                  sizeof(::Analyze) );
      instance.SetNew(&new_Analyze);
      instance.SetNewArray(&newArray_Analyze);
      instance.SetDelete(&delete_Analyze);
      instance.SetDeleteArray(&deleteArray_Analyze);
      instance.SetDestructor(&destruct_Analyze);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::Analyze*)
   {
      return GenerateInitInstanceLocal((::Analyze*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::Analyze*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
atomic_TClass_ptr Analyze::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *Analyze::Class_Name()
{
   return "Analyze";
}

//______________________________________________________________________________
const char *Analyze::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::Analyze*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int Analyze::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::Analyze*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void Analyze::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::Analyze*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *Analyze::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::Analyze*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
void Analyze::Streamer(TBuffer &R__b)
{
   // Stream an object of class Analyze.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(Analyze::Class(),this);
   } else {
      R__b.WriteClassBuffer(Analyze::Class(),this);
   }
}

//______________________________________________________________________________
void Analyze::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class Analyze.
      TClass *R__cl = ::Analyze::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fCanvasList", &fCanvasList);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fHisto1", &fHisto1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fHistTitle", &fHistTitle);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fHistAxis", &fHistAxis);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fCanvas", &fCanvas);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fFile", &fFile);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fTreeEvent", &fTreeEvent);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fTreeMD", &fTreeMD);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fTreeED", &fTreeED);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fChain", &fChain);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fEvent", &fEvent);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fBranchEvent", &fBranchEvent);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fBranchED", &fBranchED);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fBranchMD", &fBranchMD);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fHitStationMD", &fHitStationMD);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fStListMD", (void*)&fStListMD);
      R__insp.InspectMember("vector<HitStationMD>", (void*)&fStListMD, "fStListMD.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fHitStationED", &fHitStationED);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fStListED", (void*)&fStListED);
      R__insp.InspectMember("vector<HitStationED>", (void*)&fStListED, "fStListED.", false);
      TObject::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_Analyze(void *p) {
      return  p ? new(p) ::Analyze : new ::Analyze;
   }
   static void *newArray_Analyze(Long_t nElements, void *p) {
      return p ? new(p) ::Analyze[nElements] : new ::Analyze[nElements];
   }
   // Wrapper around operator delete
   static void delete_Analyze(void *p) {
      delete ((::Analyze*)p);
   }
   static void deleteArray_Analyze(void *p) {
      delete [] ((::Analyze*)p);
   }
   static void destruct_Analyze(void *p) {
      typedef ::Analyze current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::Analyze

namespace ROOT {
   void vectorlEHitStationEDgR_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void vectorlEHitStationEDgR_Dictionary();
   static void *new_vectorlEHitStationEDgR(void *p = 0);
   static void *newArray_vectorlEHitStationEDgR(Long_t size, void *p);
   static void delete_vectorlEHitStationEDgR(void *p);
   static void deleteArray_vectorlEHitStationEDgR(void *p);
   static void destruct_vectorlEHitStationEDgR(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const vector<HitStationED>*)
   {
      vector<HitStationED> *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<HitStationED>),0);
      static ::ROOT::TGenericClassInfo 
         instance("vector<HitStationED>", -2, "prec_stl/vector", 49,
                  typeid(vector<HitStationED>), DefineBehavior(ptr, ptr),
                  0, &vectorlEHitStationEDgR_Dictionary, isa_proxy, 0,
                  sizeof(vector<HitStationED>) );
      instance.SetNew(&new_vectorlEHitStationEDgR);
      instance.SetNewArray(&newArray_vectorlEHitStationEDgR);
      instance.SetDelete(&delete_vectorlEHitStationEDgR);
      instance.SetDeleteArray(&deleteArray_vectorlEHitStationEDgR);
      instance.SetDestructor(&destruct_vectorlEHitStationEDgR);
      instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::Pushback< vector<HitStationED> >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const vector<HitStationED>*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void vectorlEHitStationEDgR_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const vector<HitStationED>*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   // Wrappers around operator new
   static void *new_vectorlEHitStationEDgR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<HitStationED> : new vector<HitStationED>;
   }
   static void *newArray_vectorlEHitStationEDgR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<HitStationED>[nElements] : new vector<HitStationED>[nElements];
   }
   // Wrapper around operator delete
   static void delete_vectorlEHitStationEDgR(void *p) {
      delete ((vector<HitStationED>*)p);
   }
   static void deleteArray_vectorlEHitStationEDgR(void *p) {
      delete [] ((vector<HitStationED>*)p);
   }
   static void destruct_vectorlEHitStationEDgR(void *p) {
      typedef vector<HitStationED> current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class vector<HitStationED>

namespace ROOT {
   void vectorlEHitStationMDgR_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void vectorlEHitStationMDgR_Dictionary();
   static void *new_vectorlEHitStationMDgR(void *p = 0);
   static void *newArray_vectorlEHitStationMDgR(Long_t size, void *p);
   static void delete_vectorlEHitStationMDgR(void *p);
   static void deleteArray_vectorlEHitStationMDgR(void *p);
   static void destruct_vectorlEHitStationMDgR(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const vector<HitStationMD>*)
   {
      vector<HitStationMD> *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<HitStationMD>),0);
      static ::ROOT::TGenericClassInfo 
         instance("vector<HitStationMD>", -2, "prec_stl/vector", 49,
                  typeid(vector<HitStationMD>), DefineBehavior(ptr, ptr),
                  0, &vectorlEHitStationMDgR_Dictionary, isa_proxy, 0,
                  sizeof(vector<HitStationMD>) );
      instance.SetNew(&new_vectorlEHitStationMDgR);
      instance.SetNewArray(&newArray_vectorlEHitStationMDgR);
      instance.SetDelete(&delete_vectorlEHitStationMDgR);
      instance.SetDeleteArray(&deleteArray_vectorlEHitStationMDgR);
      instance.SetDestructor(&destruct_vectorlEHitStationMDgR);
      instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::Pushback< vector<HitStationMD> >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const vector<HitStationMD>*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void vectorlEHitStationMDgR_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const vector<HitStationMD>*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   // Wrappers around operator new
   static void *new_vectorlEHitStationMDgR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<HitStationMD> : new vector<HitStationMD>;
   }
   static void *newArray_vectorlEHitStationMDgR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<HitStationMD>[nElements] : new vector<HitStationMD>[nElements];
   }
   // Wrapper around operator delete
   static void delete_vectorlEHitStationMDgR(void *p) {
      delete ((vector<HitStationMD>*)p);
   }
   static void deleteArray_vectorlEHitStationMDgR(void *p) {
      delete [] ((vector<HitStationMD>*)p);
   }
   static void destruct_vectorlEHitStationMDgR(void *p) {
      typedef vector<HitStationMD> current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class vector<HitStationMD>

/********************************************************
* AnaDict.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableAnaDict();

extern "C" void G__set_cpp_environmentAnaDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("../src/Analyze.h");
  G__cpp_reset_tagtableAnaDict();
}
#include <new>
extern "C" int G__cpp_dllrevAnaDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* Analyze */
static int G__AnaDict_694_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   Analyze* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new Analyze[n];
     } else {
       p = new((void*) gvp) Analyze[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new Analyze;
     } else {
       p = new((void*) gvp) Analyze;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__AnaDictLN_Analyze));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AnaDict_694_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Analyze*) G__getstructoffset())->ReadFileChoice((char*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AnaDict_694_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Analyze*) G__getstructoffset())->ReadFileChoiceDebug((char*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AnaDict_694_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Analyze*) G__getstructoffset())->ReadFile((char*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AnaDict_694_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Analyze*) G__getstructoffset())->PrintTrees();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AnaDict_694_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Analyze*) G__getstructoffset())->GetMD();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AnaDict_694_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Analyze*) G__getstructoffset())->GetED();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AnaDict_694_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Analyze*) G__getstructoffset())->GetMDED();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AnaDict_694_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Analyze*) G__getstructoffset())->DrawMuons((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AnaDict_694_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Analyze*) G__getstructoffset())->DrawEvent((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AnaDict_694_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Analyze*) G__getstructoffset())->DrawStationPe((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AnaDict_694_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Analyze*) G__getstructoffset())->DrawOnePM((int) G__int(libp->para[0]), (int) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AnaDict_694_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Analyze*) G__getstructoffset())->DrawProfilesED();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AnaDict_694_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Analyze*) G__getstructoffset())->DrawProfilesMD();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AnaDict_694_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Analyze*) G__getstructoffset())->DrawOneProfileMD((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AnaDict_694_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Analyze*) G__getstructoffset())->DrawOneProfileED((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AnaDict_694_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Analyze*) G__getstructoffset())->ParticlesDistanceTime();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AnaDict_694_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Analyze*) G__getstructoffset())->DeleteFile();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AnaDict_694_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((Analyze*) G__getstructoffset())->GetListGoodFile());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AnaDict_694_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((Analyze*) G__getstructoffset())->Efficiency());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AnaDict_694_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Analyze*) G__getstructoffset())->ComputeEfficiency();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AnaDict_694_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Analyze*) G__getstructoffset())->DrawEfficiency();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AnaDict_694_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Analyze*) G__getstructoffset())->DrawOneEfficiency();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AnaDict_694_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Analyze*) G__getstructoffset())->DrawMulMDvsED((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AnaDict_694_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Analyze*) G__getstructoffset())->DrawQ((int) G__int(libp->para[0]), (int) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AnaDict_694_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Analyze*) G__getstructoffset())->DrawTotQ((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AnaDict_694_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((Analyze*) G__getstructoffset())->GetListMDED());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AnaDict_694_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         pair<float,float>* pobj;
         pair<float,float> xobj = ((Analyze*) G__getstructoffset())->DrawLDF_MD();
         pobj = new pair<float,float>(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AnaDict_694_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         pair<float,float>* pobj;
         pair<float,float> xobj = ((Analyze*) G__getstructoffset())->DrawLDF_ED();
         pobj = new pair<float,float>(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AnaDict_694_0_30(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((Analyze*) G__getstructoffset())->GetMDChargeInVEM((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AnaDict_694_0_31(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((Analyze*) G__getstructoffset())->TrigInMDCharge());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AnaDict_694_0_32(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((Analyze*) G__getstructoffset())->TrigInMuons());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AnaDict_694_0_33(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((Analyze*) G__getstructoffset())->TrigED());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AnaDict_694_0_34(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((Analyze*) G__getstructoffset())->TrigEDforQ());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AnaDict_694_0_35(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((Analyze*) G__getstructoffset())->TrigMDforQ());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AnaDict_694_0_36(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((Analyze*) G__getstructoffset())->TrigMDMuforQ());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AnaDict_694_0_37(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Analyze*) G__getstructoffset())->TestEfficiencyMu((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AnaDict_694_0_38(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Analyze*) G__getstructoffset())->TestEfficiencyVEM((float) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AnaDict_694_0_39(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Analyze*) G__getstructoffset())->TestEfficiencyED();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AnaDict_694_0_40(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Analyze*) G__getstructoffset())->NpeED();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AnaDict_694_0_41(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) Analyze::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AnaDict_694_0_42(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) Analyze::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AnaDict_694_0_43(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) Analyze::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AnaDict_694_0_44(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      Analyze::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AnaDict_694_0_48(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Analyze*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AnaDict_694_0_49(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) Analyze::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AnaDict_694_0_50(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) Analyze::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AnaDict_694_0_51(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) Analyze::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AnaDict_694_0_52(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) Analyze::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__AnaDict_694_0_53(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   Analyze* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new Analyze(*(Analyze*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__AnaDictLN_Analyze));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef Analyze G__TAnalyze;
static int G__AnaDict_694_0_54(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (Analyze*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((Analyze*) (soff+(sizeof(Analyze)*i)))->~G__TAnalyze();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (Analyze*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((Analyze*) (soff))->~G__TAnalyze();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__AnaDict_694_0_55(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   Analyze* dest = (Analyze*) G__getstructoffset();
   *dest = *(Analyze*) libp->para[0].ref;
   const Analyze& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* Analyze */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncAnaDict {
 public:
  G__Sizep2memfuncAnaDict(): p(&G__Sizep2memfuncAnaDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncAnaDict::*p)();
};

size_t G__get_sizep2memfuncAnaDict()
{
  G__Sizep2memfuncAnaDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceAnaDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__AnaDictLN_Analyze))) {
     Analyze *G__Lderived;
     G__Lderived=(Analyze*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__AnaDictLN_Analyze),G__get_linked_tagnum(&G__AnaDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableAnaDict() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__AnaDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__AnaDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__AnaDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__AnaDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__AnaDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__AnaDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__AnaDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__AnaDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__AnaDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__AnaDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("pair<UInt_t,Int_t>",117,G__get_linked_tagnum(&G__AnaDictLN_pairlEunsignedsPintcOintgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::pair<UInt_t,Int_t> >",117,G__get_linked_tagnum(&G__AnaDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<UInt_t,Int_t> >",117,G__get_linked_tagnum(&G__AnaDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__AnaDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__AnaDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__AnaDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__AnaDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<unsigned int,int> >",117,G__get_linked_tagnum(&G__AnaDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__AnaDictLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__AnaDictLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__AnaDictLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__AnaDictLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixT<Float_t>",117,G__get_linked_tagnum(&G__AnaDictLN_TMatrixTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow_const<Float_t>",117,G__get_linked_tagnum(&G__AnaDictLN_TMatrixTRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn_const<Float_t>",117,G__get_linked_tagnum(&G__AnaDictLN_TMatrixTColumn_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag_const<Float_t>",117,G__get_linked_tagnum(&G__AnaDictLN_TMatrixTDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat_const<Float_t>",117,G__get_linked_tagnum(&G__AnaDictLN_TMatrixTFlat_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub_const<Float_t>",117,G__get_linked_tagnum(&G__AnaDictLN_TMatrixTSub_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow_const<Float_t>",117,G__get_linked_tagnum(&G__AnaDictLN_TMatrixTSparseRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag_const<Float_t>",117,G__get_linked_tagnum(&G__AnaDictLN_TMatrixTSparseDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow<Float_t>",117,G__get_linked_tagnum(&G__AnaDictLN_TMatrixTRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn<Float_t>",117,G__get_linked_tagnum(&G__AnaDictLN_TMatrixTColumnlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag<Float_t>",117,G__get_linked_tagnum(&G__AnaDictLN_TMatrixTDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat<Float_t>",117,G__get_linked_tagnum(&G__AnaDictLN_TMatrixTFlatlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub<Float_t>",117,G__get_linked_tagnum(&G__AnaDictLN_TMatrixTSublEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow<Float_t>",117,G__get_linked_tagnum(&G__AnaDictLN_TMatrixTSparseRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag<Float_t>",117,G__get_linked_tagnum(&G__AnaDictLN_TMatrixTSparseDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementActionT<Float_t>",117,G__get_linked_tagnum(&G__AnaDictLN_TElementActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementPosActionT<Float_t>",117,G__get_linked_tagnum(&G__AnaDictLN_TElementPosActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__AnaDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__AnaDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__AnaDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__AnaDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__AnaDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TObjArray*>",117,G__get_linked_tagnum(&G__AnaDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__AnaDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__AnaDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*,less<string> >",117,G__get_linked_tagnum(&G__AnaDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<Double_t>",117,G__get_linked_tagnum(&G__AnaDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<Int_t>",117,G__get_linked_tagnum(&G__AnaDictLN_vectorlEintcOallocatorlEintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__AnaDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__AnaDictLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__AnaDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__AnaDictLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<int>",117,G__get_linked_tagnum(&G__AnaDictLN_vectorlEintcOallocatorlEintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<Particle>",117,G__get_linked_tagnum(&G__AnaDictLN_vectorlEParticlecOallocatorlEParticlegRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__AnaDictLN_reverse_iteratorlEvectorlEParticlecOallocatorlEParticlegRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__AnaDictLN_vectorlEParticlecOallocatorlEParticlegRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__AnaDictLN_reverse_iteratorlEvectorlEParticlecOallocatorlEParticlegRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__AnaDictLN_vectorlEParticlecOallocatorlEParticlegRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<Int_t,Double_t>",117,G__get_linked_tagnum(&G__AnaDictLN_maplEintcOdoublecOlesslEintgRcOallocatorlEpairlEconstsPintcOdoublegRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,double>",117,G__get_linked_tagnum(&G__AnaDictLN_maplEintcOdoublecOlesslEintgRcOallocatorlEpairlEconstsPintcOdoublegRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,double,less<int> >",117,G__get_linked_tagnum(&G__AnaDictLN_maplEintcOdoublecOlesslEintgRcOallocatorlEpairlEconstsPintcOdoublegRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<HitStationED>",117,G__get_linked_tagnum(&G__AnaDictLN_vectorlEHitStationEDcOallocatorlEHitStationEDgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__AnaDictLN_reverse_iteratorlEvectorlEHitStationEDcOallocatorlEHitStationEDgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__AnaDictLN_vectorlEHitStationEDcOallocatorlEHitStationEDgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__AnaDictLN_reverse_iteratorlEvectorlEHitStationEDcOallocatorlEHitStationEDgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__AnaDictLN_vectorlEHitStationEDcOallocatorlEHitStationEDgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<HitStationMD>",117,G__get_linked_tagnum(&G__AnaDictLN_vectorlEHitStationMDcOallocatorlEHitStationMDgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__AnaDictLN_reverse_iteratorlEvectorlEHitStationMDcOallocatorlEHitStationMDgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__AnaDictLN_vectorlEHitStationMDcOallocatorlEHitStationMDgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__AnaDictLN_reverse_iteratorlEvectorlEHitStationMDcOallocatorlEHitStationMDgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__AnaDictLN_vectorlEHitStationMDcOallocatorlEHitStationMDgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<float,int>",117,G__get_linked_tagnum(&G__AnaDictLN_maplEfloatcOintcOlesslEfloatgRcOallocatorlEpairlEconstsPfloatcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<float,int,less<float> >",117,G__get_linked_tagnum(&G__AnaDictLN_maplEfloatcOintcOlesslEfloatgRcOallocatorlEpairlEconstsPfloatcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<HitStationLightED>",117,G__get_linked_tagnum(&G__AnaDictLN_vectorlEHitStationLightEDcOallocatorlEHitStationLightEDgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__AnaDictLN_reverse_iteratorlEvectorlEHitStationLightEDcOallocatorlEHitStationLightEDgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__AnaDictLN_vectorlEHitStationLightEDcOallocatorlEHitStationLightEDgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__AnaDictLN_reverse_iteratorlEvectorlEHitStationLightEDcOallocatorlEHitStationLightEDgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__AnaDictLN_vectorlEHitStationLightEDcOallocatorlEHitStationLightEDgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<Station>",117,G__get_linked_tagnum(&G__AnaDictLN_vectorlEStationcOallocatorlEStationgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__AnaDictLN_reverse_iteratorlEvectorlEStationcOallocatorlEStationgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__AnaDictLN_vectorlEStationcOallocatorlEStationgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__AnaDictLN_reverse_iteratorlEvectorlEStationcOallocatorlEStationgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__AnaDictLN_vectorlEStationcOallocatorlEStationgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* Analyze */
static void G__setup_memvarAnalyze(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__AnaDictLN_Analyze));
   { Analyze *p; p=(Analyze*)0x1000; if (p) { }
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__AnaDictLN_TList),-1,-1,4,"fCanvasList=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__AnaDictLN_TList),-1,-1,4,"fHisto1=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__AnaDictLN_TList),-1,-1,4,"fHistTitle=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__AnaDictLN_TList),-1,-1,4,"fHistAxis=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__AnaDictLN_TCanvas),-1,-1,4,"fCanvas=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__AnaDictLN_TFile),-1,-1,4,"fFile=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__AnaDictLN_TTree),-1,-1,4,"fTreeEvent=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__AnaDictLN_TTree),-1,-1,4,"fTreeMD=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__AnaDictLN_TTree),-1,-1,4,"fTreeED=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__AnaDictLN_TChain),-1,-1,4,"fChain=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__AnaDictLN_Event),-1,-1,4,"fEvent=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__AnaDictLN_TBranch),-1,-1,4,"fBranchEvent=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__AnaDictLN_TBranch),-1,-1,4,"fBranchED=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__AnaDictLN_TBranch),-1,-1,4,"fBranchMD=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__AnaDictLN_HitStationMD),-1,-1,4,"fHitStationMD=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__AnaDictLN_vectorlEHitStationMDcOallocatorlEHitStationMDgRsPgR),G__defined_typename("vector<HitStationMD>"),-1,4,"fStListMD=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__AnaDictLN_HitStationED),-1,-1,4,"fHitStationED=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__AnaDictLN_vectorlEHitStationEDcOallocatorlEHitStationEDgRsPgR),G__defined_typename("vector<HitStationED>"),-1,4,"fStListED=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__AnaDictLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarAnaDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncAnalyze(void) {
   /* Analyze */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__AnaDictLN_Analyze));
   G__memfunc_setup("Analyze",724,G__AnaDict_694_0_1, 105, G__get_linked_tagnum(&G__AnaDictLN_Analyze), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ReadFileChoice",1351,G__AnaDict_694_0_2, 121, -1, -1, 0, 1, 1, 1, 0, "C - - 0 - ener", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ReadFileChoiceDebug",1838,G__AnaDict_694_0_3, 121, -1, -1, 0, 1, 1, 1, 0, "C - - 0 - ener", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ReadFile",764,G__AnaDict_694_0_4, 121, -1, -1, 0, 1, 1, 1, 0, "C - - 0 - file", "Lecture fichier", (void*) NULL, 0);
   G__memfunc_setup("PrintTrees",1040,G__AnaDict_694_0_5, 121, -1, -1, 0, 0, 1, 1, 0, "", "Affiche infos sur les 3 arbres", (void*) NULL, 0);
   G__memfunc_setup("GetMD",433,G__AnaDict_694_0_6, 121, -1, -1, 0, 0, 1, 1, 0, "", "Affichage détaillé cuve, particule, pe,..", (void*) NULL, 0);
   G__memfunc_setup("GetED",425,G__AnaDict_694_0_7, 121, -1, -1, 0, 0, 1, 1, 0, "", "Affichage détaillé cuve, particule, pe,..", (void*) NULL, 0);
   G__memfunc_setup("GetMDED",570,G__AnaDict_694_0_8, 121, -1, -1, 0, 0, 1, 1, 0, "", "Affichage succint pour ED & MD ", (void*) NULL, 0);
   G__memfunc_setup("DrawMuons",928,G__AnaDict_694_0_9, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - opt", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DrawEvent",912,G__AnaDict_694_0_10, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - nev", "Trace réseau ED & MD ->Pb Core", (void*) NULL, 0);
   G__memfunc_setup("DrawStationPe",1317,G__AnaDict_694_0_11, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - nev", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DrawOnePM",845,G__AnaDict_694_0_12, 121, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - num i - - 0 - ipm", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DrawProfilesED",1371,G__AnaDict_694_0_13, 121, -1, -1, 0, 0, 1, 1, 0, "", "Particules = f(distance_gerbe)", (void*) NULL, 0);
   G__memfunc_setup("DrawProfilesMD",1379,G__AnaDict_694_0_14, 121, -1, -1, 0, 0, 1, 1, 0, "", "Particules = f(distance_gerbe)", (void*) NULL, 0);
   G__memfunc_setup("DrawOneProfileMD",1554,G__AnaDict_694_0_15, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - num", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DrawOneProfileED",1546,G__AnaDict_694_0_16, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - num", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ParticlesDistanceTime",2145,G__AnaDict_694_0_17, 121, -1, -1, 0, 0, 1, 1, 0, "", "Profils LDF hypoth. temps", (void*) NULL, 0);
   G__memfunc_setup("DeleteFile",979,G__AnaDict_694_0_18, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetListGoodFile",1477,G__AnaDict_694_0_19, 105, -1, -1, 0, 0, 1, 1, 0, "", "-> ListGoodFile.txt ", (void*) NULL, 0);
   G__memfunc_setup("Efficiency",1013,G__AnaDict_694_0_20, 105, -1, -1, 0, 0, 1, 1, 0, "", "-> ListEfficiency.txt : E th mul_mu mul_VEM", (void*) NULL, 0);
   G__memfunc_setup("ComputeEfficiency",1746,G__AnaDict_694_0_21, 121, -1, -1, 0, 0, 1, 1, 0, "", "-> efficiency.txt : E th mul_mean ", (void*) NULL, 0);
   G__memfunc_setup("DrawEfficiency",1411,G__AnaDict_694_0_22, 121, -1, -1, 0, 0, 1, 1, 0, "", "-> Nb cuves trigger ED / MD (sig>3VEM, Nmu ...)", (void*) NULL, 0);
   G__memfunc_setup("DrawOneEfficiency",1701,G__AnaDict_694_0_23, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DrawMulMDvsED",1215,G__AnaDict_694_0_24, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - it_en", "Nb cuves trigger MD f=(Nb scint trigger ED)", (void*) NULL, 0);
   G__memfunc_setup("DrawQ",479,G__AnaDict_694_0_25, 121, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - it_en i - - 0 - mode", "en=[3,9] , mode=1 ->Sig & mode=2 -> Nmu", (void*) NULL, 0);
   G__memfunc_setup("DrawTotQ",790,G__AnaDict_694_0_26, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - mode", "mode = 1 -> SumSig  ou  mode = 2 -> Nmu", (void*) NULL, 0);
   G__memfunc_setup("GetListMDED",982,G__AnaDict_694_0_27, 105, -1, -1, 0, 0, 1, 1, 0, "", "Liste evt (Sum_signal , Sum_Npe)", (void*) NULL, 0);
   G__memfunc_setup("DrawLDF_MD",852,G__AnaDict_694_0_28, 117, G__get_linked_tagnum(&G__AnaDictLN_pairlEfloatcOfloatgR), -1, 0, 0, 1, 1, 0, "", "float -> pair <float,float>", (void*) NULL, 0);
   G__memfunc_setup("DrawLDF_ED",844,G__AnaDict_694_0_29, 117, G__get_linked_tagnum(&G__AnaDictLN_pairlEfloatcOfloatgR), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetMDChargeInVEM",1434,G__AnaDict_694_0_30, 100, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - num", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("TrigInMDCharge",1320,G__AnaDict_694_0_31, 105, -1, -1, 0, 0, 1, 1, 0, "", "trigger MD [VEM]", (void*) NULL, 0);
   G__memfunc_setup("TrigInMuons",1119,G__AnaDict_694_0_32, 105, -1, -1, 0, 0, 1, 1, 0, "", "trigger MD [Nmu]", (void*) NULL, 0);
   G__memfunc_setup("TrigED",543,G__AnaDict_694_0_33, 105, -1, -1, 0, 0, 1, 1, 0, "", "trigger ED [Npe]", (void*) NULL, 0);
   G__memfunc_setup("TrigEDforQ",951,G__AnaDict_694_0_34, 105, -1, -1, 0, 0, 1, 1, 0, "", "somme Npe -réseau ED- pour chaque gerbe !!", (void*) NULL, 0);
   G__memfunc_setup("TrigMDforQ",959,G__AnaDict_694_0_35, 102, -1, -1, 0, 0, 1, 1, 0, "", "somme sig -réseau MD- pour chaque gerbe !", (void*) NULL, 0);
   G__memfunc_setup("TrigMDMuforQ",1153,G__AnaDict_694_0_36, 102, -1, -1, 0, 0, 1, 1, 0, "", "somme Nmu -réseau MD- pour chaque gerbe !", (void*) NULL, 0);
   G__memfunc_setup("TestEfficiencyMu",1623,G__AnaDict_694_0_37, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - th", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("TestEfficiencyVEM",1661,G__AnaDict_694_0_38, 121, -1, -1, 0, 1, 1, 1, 0, "f - - 0 - th", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("TestEfficiencyED",1566,G__AnaDict_694_0_39, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NpeED",428,G__AnaDict_694_0_40, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__AnaDict_694_0_41, 85, G__get_linked_tagnum(&G__AnaDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&Analyze::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__AnaDict_694_0_42, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&Analyze::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__AnaDict_694_0_43, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&Analyze::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__AnaDict_694_0_44, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&Analyze::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__AnaDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__AnaDict_694_0_48, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__AnaDict_694_0_49, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&Analyze::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__AnaDict_694_0_50, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&Analyze::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__AnaDict_694_0_51, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&Analyze::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__AnaDict_694_0_52, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&Analyze::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("Analyze", 724, G__AnaDict_694_0_53, (int) ('i'), G__get_linked_tagnum(&G__AnaDictLN_Analyze), -1, 0, 1, 1, 1, 0, "u 'Analyze' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~Analyze", 850, G__AnaDict_694_0_54, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__AnaDict_694_0_55, (int) ('u'), G__get_linked_tagnum(&G__AnaDictLN_Analyze), -1, 1, 1, 1, 1, 0, "u 'Analyze' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncAnaDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {
}

static void G__cpp_setup_global5() {
}

static void G__cpp_setup_global6() {
}

static void G__cpp_setup_global7() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalAnaDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
  G__cpp_setup_global5();
  G__cpp_setup_global6();
  G__cpp_setup_global7();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcAnaDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__AnaDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__AnaDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__AnaDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__AnaDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__AnaDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR = { "vector<double,allocator<double> >" , 99 , -1 };
G__linked_taginfo G__AnaDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__AnaDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__AnaDictLN_TList = { "TList" , 99 , -1 };
G__linked_taginfo G__AnaDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__AnaDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__AnaDictLN_pairlEunsignedsPintcOintgR = { "pair<unsigned int,int>" , 115 , -1 };
G__linked_taginfo G__AnaDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR = { "vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >" , 99 , -1 };
G__linked_taginfo G__AnaDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >::iterator>" , 99 , -1 };
G__linked_taginfo G__AnaDictLN_TCanvas = { "TCanvas" , 99 , -1 };
G__linked_taginfo G__AnaDictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__AnaDictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__AnaDictLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__AnaDictLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__AnaDictLN_TElementActionTlEfloatgR = { "TElementActionT<float>" , 99 , -1 };
G__linked_taginfo G__AnaDictLN_TElementPosActionTlEfloatgR = { "TElementPosActionT<float>" , 99 , -1 };
G__linked_taginfo G__AnaDictLN_TMatrixTlEfloatgR = { "TMatrixT<float>" , 99 , -1 };
G__linked_taginfo G__AnaDictLN_TMatrixTRow_constlEfloatgR = { "TMatrixTRow_const<float>" , 99 , -1 };
G__linked_taginfo G__AnaDictLN_TMatrixTRowlEfloatgR = { "TMatrixTRow<float>" , 99 , -1 };
G__linked_taginfo G__AnaDictLN_TMatrixTDiag_constlEfloatgR = { "TMatrixTDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__AnaDictLN_TMatrixTColumn_constlEfloatgR = { "TMatrixTColumn_const<float>" , 99 , -1 };
G__linked_taginfo G__AnaDictLN_TMatrixTFlat_constlEfloatgR = { "TMatrixTFlat_const<float>" , 99 , -1 };
G__linked_taginfo G__AnaDictLN_TMatrixTSub_constlEfloatgR = { "TMatrixTSub_const<float>" , 99 , -1 };
G__linked_taginfo G__AnaDictLN_TMatrixTSparseRow_constlEfloatgR = { "TMatrixTSparseRow_const<float>" , 99 , -1 };
G__linked_taginfo G__AnaDictLN_TMatrixTSparseDiag_constlEfloatgR = { "TMatrixTSparseDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__AnaDictLN_TMatrixTColumnlEfloatgR = { "TMatrixTColumn<float>" , 99 , -1 };
G__linked_taginfo G__AnaDictLN_TMatrixTDiaglEfloatgR = { "TMatrixTDiag<float>" , 99 , -1 };
G__linked_taginfo G__AnaDictLN_TMatrixTFlatlEfloatgR = { "TMatrixTFlat<float>" , 99 , -1 };
G__linked_taginfo G__AnaDictLN_TMatrixTSublEfloatgR = { "TMatrixTSub<float>" , 99 , -1 };
G__linked_taginfo G__AnaDictLN_TMatrixTSparseRowlEfloatgR = { "TMatrixTSparseRow<float>" , 99 , -1 };
G__linked_taginfo G__AnaDictLN_TMatrixTSparseDiaglEfloatgR = { "TMatrixTSparseDiag<float>" , 99 , -1 };
G__linked_taginfo G__AnaDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__AnaDictLN_TTree = { "TTree" , 99 , -1 };
G__linked_taginfo G__AnaDictLN_TFile = { "TFile" , 99 , -1 };
G__linked_taginfo G__AnaDictLN_TBranch = { "TBranch" , 99 , -1 };
G__linked_taginfo G__AnaDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR = { "map<string,TObjArray*,less<string>,allocator<pair<const string,TObjArray*> > >" , 99 , -1 };
G__linked_taginfo G__AnaDictLN_vectorlEintcOallocatorlEintgRsPgR = { "vector<int,allocator<int> >" , 99 , -1 };
G__linked_taginfo G__AnaDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<int,allocator<int> >::iterator>" , 99 , -1 };
G__linked_taginfo G__AnaDictLN_vectorlEParticlecOallocatorlEParticlegRsPgR = { "vector<Particle,allocator<Particle> >" , 99 , -1 };
G__linked_taginfo G__AnaDictLN_reverse_iteratorlEvectorlEParticlecOallocatorlEParticlegRsPgRcLcLiteratorgR = { "reverse_iterator<vector<Particle,allocator<Particle> >::iterator>" , 99 , -1 };
G__linked_taginfo G__AnaDictLN_maplEintcOdoublecOlesslEintgRcOallocatorlEpairlEconstsPintcOdoublegRsPgRsPgR = { "map<int,double,less<int>,allocator<pair<const int,double> > >" , 99 , -1 };
G__linked_taginfo G__AnaDictLN_HitStationMD = { "HitStationMD" , 99 , -1 };
G__linked_taginfo G__AnaDictLN_HitStationED = { "HitStationED" , 99 , -1 };
G__linked_taginfo G__AnaDictLN_Event = { "Event" , 99 , -1 };
G__linked_taginfo G__AnaDictLN_vectorlEHitStationEDcOallocatorlEHitStationEDgRsPgR = { "vector<HitStationED,allocator<HitStationED> >" , 99 , -1 };
G__linked_taginfo G__AnaDictLN_reverse_iteratorlEvectorlEHitStationEDcOallocatorlEHitStationEDgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<HitStationED,allocator<HitStationED> >::iterator>" , 99 , -1 };
G__linked_taginfo G__AnaDictLN_vectorlEHitStationMDcOallocatorlEHitStationMDgRsPgR = { "vector<HitStationMD,allocator<HitStationMD> >" , 99 , -1 };
G__linked_taginfo G__AnaDictLN_reverse_iteratorlEvectorlEHitStationMDcOallocatorlEHitStationMDgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<HitStationMD,allocator<HitStationMD> >::iterator>" , 99 , -1 };
G__linked_taginfo G__AnaDictLN_maplEfloatcOintcOlesslEfloatgRcOallocatorlEpairlEconstsPfloatcOintgRsPgRsPgR = { "map<float,int,less<float>,allocator<pair<const float,int> > >" , 99 , -1 };
G__linked_taginfo G__AnaDictLN_vectorlEHitStationLightEDcOallocatorlEHitStationLightEDgRsPgR = { "vector<HitStationLightED,allocator<HitStationLightED> >" , 99 , -1 };
G__linked_taginfo G__AnaDictLN_reverse_iteratorlEvectorlEHitStationLightEDcOallocatorlEHitStationLightEDgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<HitStationLightED,allocator<HitStationLightED> >::iterator>" , 99 , -1 };
G__linked_taginfo G__AnaDictLN_vectorlEStationcOallocatorlEStationgRsPgR = { "vector<Station,allocator<Station> >" , 99 , -1 };
G__linked_taginfo G__AnaDictLN_reverse_iteratorlEvectorlEStationcOallocatorlEStationgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<Station,allocator<Station> >::iterator>" , 99 , -1 };
G__linked_taginfo G__AnaDictLN_TChain = { "TChain" , 99 , -1 };
G__linked_taginfo G__AnaDictLN_Analyze = { "Analyze" , 99 , -1 };
G__linked_taginfo G__AnaDictLN_pairlEfloatcOfloatgR = { "pair<float,float>" , 115 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableAnaDict() {
  G__AnaDictLN_TClass.tagnum = -1 ;
  G__AnaDictLN_TBuffer.tagnum = -1 ;
  G__AnaDictLN_TMemberInspector.tagnum = -1 ;
  G__AnaDictLN_TObject.tagnum = -1 ;
  G__AnaDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR.tagnum = -1 ;
  G__AnaDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__AnaDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__AnaDictLN_TList.tagnum = -1 ;
  G__AnaDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__AnaDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__AnaDictLN_pairlEunsignedsPintcOintgR.tagnum = -1 ;
  G__AnaDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR.tagnum = -1 ;
  G__AnaDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__AnaDictLN_TCanvas.tagnum = -1 ;
  G__AnaDictLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__AnaDictLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__AnaDictLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__AnaDictLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__AnaDictLN_TElementActionTlEfloatgR.tagnum = -1 ;
  G__AnaDictLN_TElementPosActionTlEfloatgR.tagnum = -1 ;
  G__AnaDictLN_TMatrixTlEfloatgR.tagnum = -1 ;
  G__AnaDictLN_TMatrixTRow_constlEfloatgR.tagnum = -1 ;
  G__AnaDictLN_TMatrixTRowlEfloatgR.tagnum = -1 ;
  G__AnaDictLN_TMatrixTDiag_constlEfloatgR.tagnum = -1 ;
  G__AnaDictLN_TMatrixTColumn_constlEfloatgR.tagnum = -1 ;
  G__AnaDictLN_TMatrixTFlat_constlEfloatgR.tagnum = -1 ;
  G__AnaDictLN_TMatrixTSub_constlEfloatgR.tagnum = -1 ;
  G__AnaDictLN_TMatrixTSparseRow_constlEfloatgR.tagnum = -1 ;
  G__AnaDictLN_TMatrixTSparseDiag_constlEfloatgR.tagnum = -1 ;
  G__AnaDictLN_TMatrixTColumnlEfloatgR.tagnum = -1 ;
  G__AnaDictLN_TMatrixTDiaglEfloatgR.tagnum = -1 ;
  G__AnaDictLN_TMatrixTFlatlEfloatgR.tagnum = -1 ;
  G__AnaDictLN_TMatrixTSublEfloatgR.tagnum = -1 ;
  G__AnaDictLN_TMatrixTSparseRowlEfloatgR.tagnum = -1 ;
  G__AnaDictLN_TMatrixTSparseDiaglEfloatgR.tagnum = -1 ;
  G__AnaDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__AnaDictLN_TTree.tagnum = -1 ;
  G__AnaDictLN_TFile.tagnum = -1 ;
  G__AnaDictLN_TBranch.tagnum = -1 ;
  G__AnaDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR.tagnum = -1 ;
  G__AnaDictLN_vectorlEintcOallocatorlEintgRsPgR.tagnum = -1 ;
  G__AnaDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__AnaDictLN_vectorlEParticlecOallocatorlEParticlegRsPgR.tagnum = -1 ;
  G__AnaDictLN_reverse_iteratorlEvectorlEParticlecOallocatorlEParticlegRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__AnaDictLN_maplEintcOdoublecOlesslEintgRcOallocatorlEpairlEconstsPintcOdoublegRsPgRsPgR.tagnum = -1 ;
  G__AnaDictLN_HitStationMD.tagnum = -1 ;
  G__AnaDictLN_HitStationED.tagnum = -1 ;
  G__AnaDictLN_Event.tagnum = -1 ;
  G__AnaDictLN_vectorlEHitStationEDcOallocatorlEHitStationEDgRsPgR.tagnum = -1 ;
  G__AnaDictLN_reverse_iteratorlEvectorlEHitStationEDcOallocatorlEHitStationEDgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__AnaDictLN_vectorlEHitStationMDcOallocatorlEHitStationMDgRsPgR.tagnum = -1 ;
  G__AnaDictLN_reverse_iteratorlEvectorlEHitStationMDcOallocatorlEHitStationMDgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__AnaDictLN_maplEfloatcOintcOlesslEfloatgRcOallocatorlEpairlEconstsPfloatcOintgRsPgRsPgR.tagnum = -1 ;
  G__AnaDictLN_vectorlEHitStationLightEDcOallocatorlEHitStationLightEDgRsPgR.tagnum = -1 ;
  G__AnaDictLN_reverse_iteratorlEvectorlEHitStationLightEDcOallocatorlEHitStationLightEDgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__AnaDictLN_vectorlEStationcOallocatorlEStationgRsPgR.tagnum = -1 ;
  G__AnaDictLN_reverse_iteratorlEvectorlEStationcOallocatorlEStationgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__AnaDictLN_TChain.tagnum = -1 ;
  G__AnaDictLN_Analyze.tagnum = -1 ;
  G__AnaDictLN_pairlEfloatcOfloatgR.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableAnaDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__AnaDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__AnaDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__AnaDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__AnaDictLN_TObject);
   G__get_linked_tagnum_fwd(&G__AnaDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR);
   G__get_linked_tagnum_fwd(&G__AnaDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__AnaDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__AnaDictLN_TList);
   G__get_linked_tagnum_fwd(&G__AnaDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__AnaDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__AnaDictLN_pairlEunsignedsPintcOintgR);
   G__get_linked_tagnum_fwd(&G__AnaDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__AnaDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__AnaDictLN_TCanvas);
   G__get_linked_tagnum_fwd(&G__AnaDictLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__AnaDictLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__AnaDictLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__AnaDictLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G__AnaDictLN_TElementActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__AnaDictLN_TElementPosActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__AnaDictLN_TMatrixTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__AnaDictLN_TMatrixTRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__AnaDictLN_TMatrixTRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__AnaDictLN_TMatrixTDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__AnaDictLN_TMatrixTColumn_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__AnaDictLN_TMatrixTFlat_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__AnaDictLN_TMatrixTSub_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__AnaDictLN_TMatrixTSparseRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__AnaDictLN_TMatrixTSparseDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__AnaDictLN_TMatrixTColumnlEfloatgR);
   G__get_linked_tagnum_fwd(&G__AnaDictLN_TMatrixTDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__AnaDictLN_TMatrixTFlatlEfloatgR);
   G__get_linked_tagnum_fwd(&G__AnaDictLN_TMatrixTSublEfloatgR);
   G__get_linked_tagnum_fwd(&G__AnaDictLN_TMatrixTSparseRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__AnaDictLN_TMatrixTSparseDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__AnaDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__AnaDictLN_TTree);
   G__get_linked_tagnum_fwd(&G__AnaDictLN_TFile);
   G__get_linked_tagnum_fwd(&G__AnaDictLN_TBranch);
   G__get_linked_tagnum_fwd(&G__AnaDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__AnaDictLN_vectorlEintcOallocatorlEintgRsPgR);
   G__get_linked_tagnum_fwd(&G__AnaDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__AnaDictLN_vectorlEParticlecOallocatorlEParticlegRsPgR);
   G__get_linked_tagnum_fwd(&G__AnaDictLN_reverse_iteratorlEvectorlEParticlecOallocatorlEParticlegRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__AnaDictLN_maplEintcOdoublecOlesslEintgRcOallocatorlEpairlEconstsPintcOdoublegRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__AnaDictLN_HitStationMD);
   G__get_linked_tagnum_fwd(&G__AnaDictLN_HitStationED);
   G__get_linked_tagnum_fwd(&G__AnaDictLN_Event);
   G__get_linked_tagnum_fwd(&G__AnaDictLN_vectorlEHitStationEDcOallocatorlEHitStationEDgRsPgR);
   G__get_linked_tagnum_fwd(&G__AnaDictLN_reverse_iteratorlEvectorlEHitStationEDcOallocatorlEHitStationEDgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__AnaDictLN_vectorlEHitStationMDcOallocatorlEHitStationMDgRsPgR);
   G__get_linked_tagnum_fwd(&G__AnaDictLN_reverse_iteratorlEvectorlEHitStationMDcOallocatorlEHitStationMDgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__AnaDictLN_maplEfloatcOintcOlesslEfloatgRcOallocatorlEpairlEconstsPfloatcOintgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__AnaDictLN_vectorlEHitStationLightEDcOallocatorlEHitStationLightEDgRsPgR);
   G__get_linked_tagnum_fwd(&G__AnaDictLN_reverse_iteratorlEvectorlEHitStationLightEDcOallocatorlEHitStationLightEDgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__AnaDictLN_vectorlEStationcOallocatorlEStationgRsPgR);
   G__get_linked_tagnum_fwd(&G__AnaDictLN_reverse_iteratorlEvectorlEStationcOallocatorlEStationgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__AnaDictLN_TChain);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__AnaDictLN_Analyze),sizeof(Analyze),-1,292096,(char*)NULL,G__setup_memvarAnalyze,G__setup_memfuncAnalyze);
   G__get_linked_tagnum_fwd(&G__AnaDictLN_pairlEfloatcOfloatgR);
}
extern "C" void G__cpp_setupAnaDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupAnaDict()");
  G__set_cpp_environmentAnaDict();
  G__cpp_setup_tagtableAnaDict();

  G__cpp_setup_inheritanceAnaDict();

  G__cpp_setup_typetableAnaDict();

  G__cpp_setup_memvarAnaDict();

  G__cpp_setup_memfuncAnaDict();
  G__cpp_setup_globalAnaDict();
  G__cpp_setup_funcAnaDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncAnaDict();
  return;
}
class G__cpp_setup_initAnaDict {
  public:
    G__cpp_setup_initAnaDict() { G__add_setup_func("AnaDict",(G__incsetup)(&G__cpp_setupAnaDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initAnaDict() { G__remove_setup_func("AnaDict"); }
};
G__cpp_setup_initAnaDict G__cpp_setup_initializerAnaDict;

