/********************************************************************
* EventDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error EventDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableEventDict();
extern void G__cpp_setup_inheritanceEventDict();
extern void G__cpp_setup_typetableEventDict();
extern void G__cpp_setup_memvarEventDict();
extern void G__cpp_setup_globalEventDict();
extern void G__cpp_setup_memfuncEventDict();
extern void G__cpp_setup_funcEventDict();
extern void G__set_cpp_environmentEventDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "../src/Event.h"
#include "../src/Station.h"
#include "../src/Array.h"
#include "../src/Particle.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__EventDictLN_TClass;
extern G__linked_taginfo G__EventDictLN_TBuffer;
extern G__linked_taginfo G__EventDictLN_TMemberInspector;
extern G__linked_taginfo G__EventDictLN_TObject;
extern G__linked_taginfo G__EventDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__EventDictLN_string;
extern G__linked_taginfo G__EventDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__EventDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EventDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__EventDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EventDictLN_maplEintcOintcOlesslEintgRcOallocatorlEpairlEconstsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__EventDictLN_Particle;
extern G__linked_taginfo G__EventDictLN_ParticleInTank;
extern G__linked_taginfo G__EventDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__EventDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EventDictLN_ParticleInScint;
extern G__linked_taginfo G__EventDictLN_Station;
extern G__linked_taginfo G__EventDictLN_SampStation;
extern G__linked_taginfo G__EventDictLN_vectorlEParticlecOallocatorlEParticlegRsPgR;
extern G__linked_taginfo G__EventDictLN_reverse_iteratorlEvectorlEParticlecOallocatorlEParticlegRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EventDictLN_PMT_MD;
extern G__linked_taginfo G__EventDictLN_maplEintcOdoublecOlesslEintgRcOallocatorlEpairlEconstsPintcOdoublegRsPgRsPgR;
extern G__linked_taginfo G__EventDictLN_HitStationMD;
extern G__linked_taginfo G__EventDictLN_PMT_ED;
extern G__linked_taginfo G__EventDictLN_HitStationED;
extern G__linked_taginfo G__EventDictLN_HitStationLightED;
extern G__linked_taginfo G__EventDictLN_Event;
extern G__linked_taginfo G__EventDictLN_vectorlEHitStationEDcOallocatorlEHitStationEDgRsPgR;
extern G__linked_taginfo G__EventDictLN_reverse_iteratorlEvectorlEHitStationEDcOallocatorlEHitStationEDgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EventDictLN_vectorlEHitStationMDcOallocatorlEHitStationMDgRsPgR;
extern G__linked_taginfo G__EventDictLN_reverse_iteratorlEvectorlEHitStationMDcOallocatorlEHitStationMDgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EventDictLN_EventRec;
extern G__linked_taginfo G__EventDictLN_maplEfloatcOintcOlesslEfloatgRcOallocatorlEpairlEconstsPfloatcOintgRsPgRsPgR;
extern G__linked_taginfo G__EventDictLN_vectorlEHitStationLightEDcOallocatorlEHitStationLightEDgRsPgR;
extern G__linked_taginfo G__EventDictLN_reverse_iteratorlEvectorlEHitStationLightEDcOallocatorlEHitStationLightEDgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EventDictLN_Array;
extern G__linked_taginfo G__EventDictLN_vectorlEStationcOallocatorlEStationgRsPgR;
extern G__linked_taginfo G__EventDictLN_reverse_iteratorlEvectorlEStationcOallocatorlEStationgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
