/********************************************************************
* ShowerROOTDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ShowerROOTDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableShowerROOTDict();
extern void G__cpp_setup_inheritanceShowerROOTDict();
extern void G__cpp_setup_typetableShowerROOTDict();
extern void G__cpp_setup_memvarShowerROOTDict();
extern void G__cpp_setup_globalShowerROOTDict();
extern void G__cpp_setup_memfuncShowerROOTDict();
extern void G__cpp_setup_funcShowerROOTDict();
extern void G__set_cpp_environmentShowerROOTDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "../src/Shower_ROOT.h"
#include "../src/ShowerGrnd_ROOT.h"
#include "../src/ShowerProf_ROOT.h"
#include "../src/HeaderCorsika_ROOT.h"
#include "../src/PartGrnd_ROOT.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__ShowerROOTDictLN_TClass;
extern G__linked_taginfo G__ShowerROOTDictLN_TBuffer;
extern G__linked_taginfo G__ShowerROOTDictLN_TMemberInspector;
extern G__linked_taginfo G__ShowerROOTDictLN_TObject;
extern G__linked_taginfo G__ShowerROOTDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__ShowerROOTDictLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__ShowerROOTDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__ShowerROOTDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ShowerROOTDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__ShowerROOTDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ShowerROOTDictLN_ProgName;
extern G__linked_taginfo G__ShowerROOTDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__ShowerROOTDictLN_TFile;
extern G__linked_taginfo G__ShowerROOTDictLN_TTree;
extern G__linked_taginfo G__ShowerROOTDictLN_TBranch;
extern G__linked_taginfo G__ShowerROOTDictLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__ShowerROOTDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__ShowerROOTDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ShowerROOTDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__ShowerROOTDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__ShowerROOTDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__ShowerROOTDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__ShowerROOTDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__ShowerROOTDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__ShowerROOTDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__ShowerROOTDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__ShowerROOTDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__ShowerROOTDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__ShowerROOTDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__ShowerROOTDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__ShowerROOTDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__ShowerROOTDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__ShowerROOTDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__ShowerROOTDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__ShowerROOTDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__ShowerROOTDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__ShowerROOTDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__ShowerROOTDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__ShowerROOTDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__ShowerROOTDictLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__ShowerROOTDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ShowerROOTDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__ShowerROOTDictLN_Header_ROOT;
extern G__linked_taginfo G__ShowerROOTDictLN_ShowerProperties;
extern G__linked_taginfo G__ShowerROOTDictLN_PartGrnd_ROOT;
extern G__linked_taginfo G__ShowerROOTDictLN_HeaderCorsika_ROOT;
extern G__linked_taginfo G__ShowerROOTDictLN_ShowerGrnd_ROOT;
extern G__linked_taginfo G__ShowerROOTDictLN_ShowerProf_ROOT;
extern G__linked_taginfo G__ShowerROOTDictLN_Shower_ROOT;

/* STUB derived class for protected member access */
