/********************************************************************
* AnaDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error AnaDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableAnaDict();
extern void G__cpp_setup_inheritanceAnaDict();
extern void G__cpp_setup_typetableAnaDict();
extern void G__cpp_setup_memvarAnaDict();
extern void G__cpp_setup_globalAnaDict();
extern void G__cpp_setup_memfuncAnaDict();
extern void G__cpp_setup_funcAnaDict();
extern void G__set_cpp_environmentAnaDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "../src/Analyze.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__AnaDictLN_TClass;
extern G__linked_taginfo G__AnaDictLN_TBuffer;
extern G__linked_taginfo G__AnaDictLN_TMemberInspector;
extern G__linked_taginfo G__AnaDictLN_TObject;
extern G__linked_taginfo G__AnaDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__AnaDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__AnaDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__AnaDictLN_TList;
extern G__linked_taginfo G__AnaDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__AnaDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__AnaDictLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__AnaDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__AnaDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__AnaDictLN_TCanvas;
extern G__linked_taginfo G__AnaDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__AnaDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__AnaDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__AnaDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__AnaDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__AnaDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__AnaDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__AnaDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__AnaDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__AnaDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__AnaDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__AnaDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__AnaDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__AnaDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__AnaDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__AnaDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__AnaDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__AnaDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__AnaDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__AnaDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__AnaDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__AnaDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__AnaDictLN_TTree;
extern G__linked_taginfo G__AnaDictLN_TFile;
extern G__linked_taginfo G__AnaDictLN_TBranch;
extern G__linked_taginfo G__AnaDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__AnaDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__AnaDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__AnaDictLN_vectorlEParticlecOallocatorlEParticlegRsPgR;
extern G__linked_taginfo G__AnaDictLN_reverse_iteratorlEvectorlEParticlecOallocatorlEParticlegRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__AnaDictLN_maplEintcOdoublecOlesslEintgRcOallocatorlEpairlEconstsPintcOdoublegRsPgRsPgR;
extern G__linked_taginfo G__AnaDictLN_HitStationMD;
extern G__linked_taginfo G__AnaDictLN_HitStationED;
extern G__linked_taginfo G__AnaDictLN_Event;
extern G__linked_taginfo G__AnaDictLN_vectorlEHitStationEDcOallocatorlEHitStationEDgRsPgR;
extern G__linked_taginfo G__AnaDictLN_reverse_iteratorlEvectorlEHitStationEDcOallocatorlEHitStationEDgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__AnaDictLN_vectorlEHitStationMDcOallocatorlEHitStationMDgRsPgR;
extern G__linked_taginfo G__AnaDictLN_reverse_iteratorlEvectorlEHitStationMDcOallocatorlEHitStationMDgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__AnaDictLN_vectorlEStationcOallocatorlEStationgRsPgR;
extern G__linked_taginfo G__AnaDictLN_reverse_iteratorlEvectorlEStationcOallocatorlEStationgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__AnaDictLN_TChain;
extern G__linked_taginfo G__AnaDictLN_Analyze;

/* STUB derived class for protected member access */
